<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Ninjasoft</Authors>
    <Company>Ninjasoft</Company>
    <Description>A client to make using the Azure DevOps REST API easier</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://github.com/ninjacoder88/azure-devops-client</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>Rollback to Newtonsoft.Json as System.Text.Json doesn't support certain objects</PackageReleaseNotes>
    <PackageIcon>transparent-ninjasoft-nuget.png</PackageIcon>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>2.3.5</AssemblyVersion>
    <FileVersion>2.3.5</FileVersion>
    <Version>2.3.5</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ninjasoft.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="transparent-ninjasoft-nuget.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
